apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: apps
  labels:
    k8s-app: wordpress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:4.9.1-php5.6-apache
          ports:
            - name: http
              containerPort: 80
          env:
          - name: WORDPRESS_DB_HOST
            valueFrom:
              secretKeyRef:
                name: mysql-host
                key: host
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-user
                key: user
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password