# Imagen base
FROM ubuntu:15.04
# Autor
LABEL maintainer="jariepei@gmail.com"
# Comandos ejecutados durante la creación del contenedor
RUN apt-get update
# Comando que se ejecuta durante la ejecución del contenedor.
CMD ["echo","Hello world"]